### ISSUE TITLE
can't sign up for an account - how can i help?

### ISSUE THREAD

**Issue by Sabotnik** [lolcommits/lolcommits-dot-com#1]
Hello contributors!

I recently completed theFirehose Project apprenticeship and Ken Mazaika suggested working on this project for fun. How can I help? I know the main login isn't working currently but not sure where to begin to fix it - seems like the hosting has been changed or tweaked? Any help would be appreciated to get me started...

**Comment by matthutchinson** [comment]
So, I recently fixed a few things in this app and we decided to move it into the lolcommits organization account here at GitHub (hence its missing PR and issue history).

Full disclosure, i'm a mentor at thFirehose Project too :smile:

**Comment by matthutchinson** [comment]
Ps.. we have a [long running todo](https://github.com/mroth/lolcommits/blob/master/CHANGELOG.md#version-history) on the lolcommits gem itself, to extract all plugins to separate gems and build a new plugin eco system - cleaning the base gem up, and making it easier to release new features for it.

**Comment by kenmazaika** [comment]
Hey Dave -

Like Matt says, the first step is probably to get it running on your local machine and working with the lolcommits gem.  This isn't going to work in your vagrant environment.  If you're on a mac you can [install stuff on your base machine here](https://github.com/FirehoseWeekend/install-guide/blob/master/mac.md).  Although I kind of hate the [railsinstaller on windows](http://railsinstaller.org/en), if you're on windows and want to use lolcommits I think that's your only option.  

I just added you to the heroku repo.  Why don't you look through the heroku logs and try to figure out what error message is happening when you try to sign up?

From there come up with some proposals on how to fix it.

**Comment by matthutchinson** [comment]
Will close this issue soon, unless theres a real need here ..
